databases:
  - name: projectnest-db
    plan: free
services:
  - type: web
    name: projectnest-api
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python manage.py seed_store
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: DATABASE_URL
        fromDatabase: {name: projectnest-db, property: connectionString}
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: FRONTEND_ORIGIN_REGEXES
        value: ^https://.*\.vercel\.app$
      - key: GROQ_API_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
