import { useMemo, useState } from 'react'
import { ArrowRight, CheckCircle2, Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import api from '../api'
import { useStore } from '../StoreContext'

const emptyForm = { customer_name: '', email: '', phone: '', address: '', city: '', state: '', postal_code: '', payment_method: 'cod', coins: 0 }
export default function Cart() {
  const { cart, setCart, updateCart, removeFromCart, authenticated, user } = useStore(); const [checkout, setCheckout] = useState(false); const [form, setForm] = useState(() => ({ ...emptyForm, email: user?.email || '' })); const [busy, setBusy] = useState(false); const [order, setOrder] = useState(null); const [error, setError] = useState('')
  const subtotal = useMemo(() => cart.reduce((sum, x) => sum + Number(x.product.sale_price) * x.quantity, 0), [cart]); const shipping = subtotal >= 1999 ? 0 : 99; const coins = Math.min(Number(form.coins) || 0, user?.reward_coins || 0, Math.floor((subtotal + shipping) * .2)); const total = subtotal + shipping - coins
  const submit = async e => { e.preventDefault(); setBusy(true); setError(''); try { const payload = { ...form, coins, items: authenticated ? [] : cart.map(x => ({ product_id: x.product.id, quantity: x.quantity })) }; const { data } = await api.post('/checkout/', payload); setOrder(data); setCart([]); localStorage.removeItem('guest_cart') } catch (e) { setError(e.response?.data?.detail || 'Checkout could not be completed.') } finally { setBusy(false) } }
  if (order) return <div className="container page success"><CheckCircle2 /><span className="kicker">Order confirmed</span><h1>Thank you for building with us.</h1><p>Your order <b>{order.number}</b> is confirmed. We sent the details to {order.email}.</p><div className="order-total"><span>Total paid / due</span><strong>₹{Number(order.total).toLocaleString('en-IN')}</strong></div><Link to="/shop" className="button primary">Explore more projects <ArrowRight /></Link></div>
  if (!cart.length) return <div className="container page empty cart-empty"><ShoppingBag /><h1>Your cart is ready for an idea.</h1><p>Choose a project kit and start building something worth showing.</p><Link className="button primary" to="/shop">Browse projects <ArrowRight /></Link></div>
  return <div className="container page"><div className="page-title"><span className="kicker">Your build list</span><h1>Shopping cart</h1></div><div className="cart-layout"><div className="cart-list">{cart.map(item => <article className="cart-item" key={item.product.id}><img src={item.product.image_url} alt="" /><div className="cart-item-info"><small>{item.product.category_name}</small><Link to={`/products/${item.product.slug}`}><h3>{item.product.name}</h3></Link><span className="stock in-stock">{item.product.stock_label}</span></div><div className="stepper"><button onClick={() => updateCart(item.product.id, item.quantity - 1)}><Minus /></button><b>{item.quantity}</b><button onClick={() => updateCart(item.product.id, item.quantity + 1)}><Plus /></button></div><strong>₹{(Number(item.product.sale_price) * item.quantity).toLocaleString('en-IN')}</strong><button className="remove" onClick={() => removeFromCart(item.product.id)} aria-label="Remove"><Trash2 /></button></article>)}</div><aside className="summary-card"><h2>Order summary</h2><div><span>Subtotal</span><b>₹{subtotal.toLocaleString('en-IN')}</b></div><div><span>Shipping</span><b>{shipping ? `₹${shipping}` : 'FREE'}</b></div>{coins > 0 && <div><span>Reward coins</span><b>−₹{coins}</b></div>}<hr /><div className="total"><span>Total</span><strong>₹{total.toLocaleString('en-IN')}</strong></div><small>Tax included. Secure checkout.</small><button className="button primary wide" onClick={() => setCheckout(true)}>Continue to checkout <ArrowRight /></button>{shipping > 0 && <p>Add ₹{(1999 - subtotal).toLocaleString('en-IN')} more for free shipping.</p>}</aside></div>
    {checkout && <div className="modal-backdrop" onMouseDown={() => setCheckout(false)}><form className="checkout-modal" onSubmit={submit} onMouseDown={e => e.stopPropagation()}><button type="button" className="close-text" onClick={() => setCheckout(false)}>Close</button><span className="kicker">Secure checkout</span><h2>Delivery details</h2><div className="form-grid">{[['customer_name','Full name'],['email','Email'],['phone','Phone'],['address','Street address'],['city','City'],['state','State'],['postal_code','PIN code']].map(([name,label]) => <label key={name} className={name === 'address' ? 'full' : ''}>{label}<input required type={name === 'email' ? 'email' : 'text'} value={form[name]} onChange={e => setForm({ ...form, [name]: e.target.value })} /></label>)}</div>{authenticated && user?.reward_coins > 0 && <label>Redeem coins (available: {user.reward_coins})<input type="number" min="0" max={user.reward_coins} value={form.coins} onChange={e => setForm({ ...form, coins: e.target.value })} /></label>}<fieldset><legend>Payment method</legend><label><input type="radio" checked={form.payment_method === 'cod'} onChange={() => setForm({...form, payment_method:'cod'})} /> Cash on delivery</label><label><input type="radio" checked={form.payment_method === 'razorpay'} onChange={() => setForm({...form, payment_method:'razorpay'})} /> Razorpay (configure keys)</label></fieldset>{error && <p className="form-error">{error}</p>}<button className="button primary wide" disabled={busy}>{busy ? 'Placing order…' : `Place order · ₹${total.toLocaleString('en-IN')}`}</button></form></div>}
  </div>
}

