import { useEffect, useState } from 'react'
import { ArrowRight, Bot, Box, Cpu, ShieldCheck, Sparkles, Star, Truck } from 'lucide-react'
import { Link } from 'react-router-dom'
import api from '../api'
import ProductCard from '../components/ProductCard'

const iconFor = (name) => name.includes('Robot') ? '🤖' : name.includes('Web') ? '⌘' : name.includes('Mobile') ? '▣' : name.includes('Energy') ? '☀' : name.includes('Security') ? '⌁' : name.includes('Data') ? '◫' : name.includes('AI') ? '✦' : name.includes('IoT') ? '⌁' : name.includes('Electronic') ? 'ϟ' : '◉'
export default function Home() {
  const [categories, setCategories] = useState([]); const [featured, setFeatured] = useState([])
  useEffect(() => { api.get('/categories/').then(r => setCategories(r.data)); api.get('/products/?featured=true&page_size=8').then(r => setFeatured(r.data.results || r.data)) }, [])
  return <>
    <section className="hero"><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><Sparkles size={15} /> Ideas deserve to be built</div><h1>Learn deeply.<br /><em>Build boldly.</em></h1><p>Curated project kits that turn ambitious ideas into portfolio-ready builds—components, code, and guidance included.</p><div className="hero-buttons"><Link to="/shop" className="button primary">Explore projects <ArrowRight /></Link><a href="#categories" className="button ghost">Browse categories</a></div><div className="hero-proof"><div className="avatars"><span>AK</span><span>RM</span><span>PS</span><span>+2k</span></div><div><div className="rating"><Star size={15} fill="currentColor" /><Star size={15} fill="currentColor" /><Star size={15} fill="currentColor" /><Star size={15} fill="currentColor" /><Star size={15} fill="currentColor" /></div><small>Loved by student builders</small></div></div></div><div className="hero-visual"><div className="orb one" /><div className="orb two" /><div className="kit-card"><div className="kit-top"><span>FEATURED BUILD</span><Cpu /></div><div className="circuit"><div className="board"><b>PN</b><i /><i /><i /><i /></div><span className="wire w1" /><span className="wire w2" /><span className="sensor">●</span></div><h3>Smart Automation Kit</h3><p>From concept to working prototype</p><div className="progress"><span /></div></div><div className="float-card fc-one"><ShieldCheck /> Tested components</div><div className="float-card fc-two"><Bot /> AI project guide</div></div></div></section>
    <section className="trust-strip"><div className="container"><div><Truck /> <span><b>Fast dispatch</b><small>Within 1–2 business days</small></span></div><div><Box /> <span><b>Complete kits</b><small>Everything essential included</small></span></div><div><ShieldCheck /> <span><b>Quality checked</b><small>Every component is tested</small></span></div><div><Bot /> <span><b>Smart assistance</b><small>Answers when you need them</small></span></div></div></section>
    <section className="section container" id="categories"><div className="section-heading"><div><span className="kicker">Find your next build</span><h2>Explore by category</h2></div><Link to="/shop">View all projects <ArrowRight /></Link></div><div className="category-grid">{categories.map(c => <Link key={c.id} to={`/shop?category=${c.slug}`} className="category-card" style={{'--accent': c.color}}><span className="category-icon">{iconFor(c.name)}</span><h3>{c.name}</h3><p>{c.product_count} projects</p><ArrowRight /></Link>)}</div></section>
    <section className="section featured-section"><div className="container"><div className="section-heading"><div><span className="kicker">Popular right now</span><h2>Featured projects</h2></div><Link to="/shop">Shop all <ArrowRight /></Link></div><div className="product-grid">{featured.slice(0, 8).map(p => <ProductCard key={p.id} product={p} />)}</div></div></section>
    <section className="section container" id="why-us"><div className="builder-banner"><div><span className="kicker">A better way to learn</span><h2>Don’t just watch.<br />Make it work.</h2><p>Every kit is designed around practical outcomes, clear milestones, and the kind of proof that belongs in your portfolio.</p><Link to="/shop" className="button light-btn">Find your project <ArrowRight /></Link></div><div className="stats"><div><strong>100+</strong><span>Project kits</span></div><div><strong>10</strong><span>Learning tracks</span></div><div><strong>4.7</strong><span>Average rating</span></div><div><strong>24/7</strong><span>AI guidance</span></div></div></div></section>
  </>
}

